[package]
name = "rustconsole-codec-ffmpeg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[target.'cfg(not(windows))'.dependencies]
ffmpeg-next.workspace = true

[target.'cfg(windows)'.dependencies]
ffmpeg-next = { workspace = true, features = ["static"] }
windows.workspace = true
